from pydantic import Field
from typing import Any

from ...model import Empty, WSBaseModel

class CPE(WSBaseModel):
    pk                          : int           = Field(..., alias='cpe_pk')
    access_login                : str   | Empty = Field(default_factory=Empty, alias='cpe_access_login')
    access_password             : str   | Empty = Field(default_factory=Empty, alias='cpe_access_password')
    access_port                 : int   | Empty = Field(default_factory=Empty, alias='cpe_access_port')
    address_pk                  : int   | Empty = Field(default_factory=Empty, alias='address_pk')
    attributes_pk               : int   | Empty = Field(default_factory=Empty, alias='attributes_pk')
    auth_type                   : int   | Empty = Field(default_factory=Empty, alias='cpe_auth_type')
    circuit_id                  : str   | Empty = Field(default_factory=Empty, alias='cpe_circuit_id')
    client_pk                   : int   | Empty = Field(default_factory=Empty, alias='client_pk')
    client_show_contract        : bool  | Empty = Field(default_factory=Empty, alias='cpe_client_show_contract')
    client_show                 : bool  | Empty = Field(default_factory=Empty, alias='cpe_client_show')
    client_show_usage           : bool  | Empty = Field(default_factory=Empty, alias='cpe_client_show_usage')
    contract_pk                 : int   | Empty = Field(default_factory=Empty, alias='contract_pk')
    dp_pk                       : int   | Empty = Field(default_factory=Empty, alias='dp_pk')
    free                        : bool  | Empty = Field(default_factory=Empty, alias='cpe_free')
    kv                          : Any   | Empty = Field(default_factory=Empty, alias='cpe_kv')
    mac_status                  : int   | Empty = Field(default_factory=Empty, alias='cpe_mac_status')
    mac                         : str   | Empty = Field(default_factory=Empty, alias='cpe_mac')
    nas_pk                      : int   | Empty = Field(default_factory=Empty, alias='nas_pk')
    obs                         : str   | Empty = Field(default_factory=Empty, alias='cpe_obs')
    plan_pk                     : int   | Empty = Field(default_factory=Empty, alias='plan_pk')
    pool_v4_pk                  : int   | Empty = Field(default_factory=Empty, alias='pool_v4_pk')
    pool_v6_px_pk               : int   | Empty = Field(default_factory=Empty, alias='pool_v6_px_pk')
    pool_v6_pd_pk               : int   | Empty = Field(default_factory=Empty, alias='pool_v6_pd_pk')
    product_type                : int   | Empty = Field(default_factory=Empty, alias='cpe_product_type')
    prov_pk                     : int   | Empty = Field(default_factory=Empty, alias='prov_pk')
    service_type                : int   | Empty = Field(default_factory=Empty, alias='cpe_service_type')
    status                      : int   | Empty = Field(default_factory=Empty, alias='cpe_status')
    transmission_type           : int   | Empty = Field(default_factory=Empty, alias='cpe_transmission_type')
    technology_type             : int   | Empty = Field(default_factory=Empty, alias='cpe_technology_type')
    username                    : str   | Empty = Field(default_factory=Empty, alias='cpe_username')
    v4_ip_status                : int   | Empty = Field(default_factory=Empty, alias='cpe_v4_ip_status')
    v4_ip                       : str   | Empty = Field(default_factory=Empty, alias='cpe_v4_ip')
    v6_px_status                : int   | Empty = Field(default_factory=Empty, alias='cpe_v6_px_status')
    v6_px                       : str   | Empty = Field(default_factory=Empty, alias='cpe_v6_px')
    v6_pd_status                : int   | Empty = Field(default_factory=Empty, alias='cpe_v6_pd_status')
    v6_pd                       : str   | Empty = Field(default_factory=Empty, alias='cpe_v6_pd')
    wifi_encryption_type        : int   | Empty = Field(default_factory=Empty, alias='cpe_wifi_encryption_type')

class CPEExtended(CPE):
    pk                          : int           = Field(..., alias='cpe_pk')
    address                     : str   | Empty = Field(default_factory=Empty, alias='address')
    address_completation        : str   | Empty = Field(default_factory=Empty, alias='address_completation')
    address_latitude            : str   | Empty = Field(default_factory=Empty, alias='address_latitude')
    address_longitude           : str   | Empty = Field(default_factory=Empty, alias='address_longitude')
    # Localização do PRÓPRIO cpe (onde o equipamento foi instalado, ex:
    # capturada via GPS pelo técnico) — campo distinto de
    # address_latitude/longitude (que é do endereço cadastral vinculado,
    # via join). Confirmado como campo de verdade em /aaa_ctl/cpe/list e
    # aceito em /aaa_ctl/cpe/update (doc oficial); faltava no pacote
    # original, então uma localização recém-salva nunca voltava na leitura.
    cpe_latitude                : str   | Empty = Field(default_factory=Empty, alias='cpe_latitude')
    cpe_longitude               : str   | Empty = Field(default_factory=Empty, alias='cpe_longitude')
    address_neighborhood        : str   | Empty = Field(default_factory=Empty, alias='address_neighborhood')
    address_number              : str   | Empty = Field(default_factory=Empty, alias='address_number')
    address_province            : str   | Empty = Field(default_factory=Empty, alias='address_province')
    address_state               : str   | Empty = Field(default_factory=Empty, alias='address_state')
    address_zipcode             : str   | Empty = Field(default_factory=Empty, alias='address_zipcode')
    client_complete_name        : str   | Empty = Field(default_factory=Empty, alias='client_complete_name')
    client_doc1                 : str   | Empty = Field(default_factory=Empty, alias='client_doc1')
    client_doc2                 : str   | Empty = Field(default_factory=Empty, alias='client_doc2')
    client_lastname             : str   | Empty = Field(default_factory=Empty, alias='client_lastname')
    client_name                 : str   | Empty = Field(default_factory=Empty, alias='client_name')
    client_status               : int   | Empty = Field(default_factory=Empty, alias='client_status')
    client_type                 : int   | Empty = Field(default_factory=Empty, alias='client_type')
    contract_amount             : float | Empty = Field(default_factory=Empty, alias='contract_amount')
    contract_deleted            : bool  | Empty = Field(default_factory=Empty, alias='contract_deleted')
    contract_number             : int   | Empty = Field(default_factory=Empty, alias='contract_number')
    contract_pay_day            : int   | Empty = Field(default_factory=Empty, alias='contract_pay_day')
    contract_status             : int   | Empty = Field(default_factory=Empty, alias='contract_status')
    date_acct                   : Any   | Empty = Field(default_factory=Empty, alias='cpe_date_acct')
    date_acct_sec               : Any   | Empty = Field(default_factory=Empty, alias='cpe_date_acct_sec')
    date_add                    : Any   | Empty = Field(default_factory=Empty, alias='cpe_date_add')
    date_auth                   : Any   | Empty = Field(default_factory=Empty, alias='cpe_date_auth')
    date_auth_sec               : Any   | Empty = Field(default_factory=Empty, alias='cpe_date_auth_sec')
    date_del                    : Any   | Empty = Field(default_factory=Empty, alias='cpe_date_del')
    date_edt                    : Any   | Empty = Field(default_factory=Empty, alias='cpe_date_edt')
    date_last                   : Any   | Empty = Field(default_factory=Empty, alias='cpe_date_last')
    date_start                  : Any   | Empty = Field(default_factory=Empty, alias='cpe_date_start')
    deleted                     : Any   | Empty = Field(default_factory=Empty, alias='cpe_deleted')
    dp_id                       : str   | Empty = Field(default_factory=Empty, alias='dp_id')
    dp_name                     : str   | Empty = Field(default_factory=Empty, alias='dp_name')
    dp_port                     : Any   | Empty = Field(default_factory=Empty, alias='dp_port')
    lending                     : Any   | Empty = Field(default_factory=Empty, alias='lending')
    mac_last                    : Any   | Empty = Field(default_factory=Empty, alias='mac_last')
    nas_addr                    : Any   | Empty = Field(default_factory=Empty, alias='nas_addr')
    nas_interface               : Any   | Empty = Field(default_factory=Empty, alias='nas_interface')
    nas_name                    : Any   | Empty = Field(default_factory=Empty, alias='nas_name')
    notice                      : Any   | Empty = Field(default_factory=Empty, alias='notice')
    offices_pk                  : Any   | Empty = Field(default_factory=Empty, alias='offices_pk')
    # Alias correto é "cpe_password" (senha PPPoE real, pareada com
    # "cpe_username") — confirmado na doc oficial
    # (apidoc.brbyte.com/#post-/aaa_ctl/cpe/list). O pacote original vinha
    # com alias="password" (bare), que nunca bate com a chave de verdade
    # da resposta ("cpe_password"), então este campo nunca era
    # preenchido — sempre Empty, mesmo com o dado presente na resposta.
    password                    : Any   | Empty = Field(default_factory=Empty, alias='cpe_password')
    plan_name                   : Any   | Empty = Field(default_factory=Empty, alias='plan_name')
    pool_v4_family              : int   | Empty = Field(default_factory=Empty, alias='pool_v4_family')
    pool_v4_name                : str   | Empty = Field(default_factory=Empty, alias='pool_v4_name')
    pool_v4_network             : str   | Empty = Field(default_factory=Empty, alias='pool_v4_network')
    pool_v4_pool                : str   | Empty = Field(default_factory=Empty, alias='pool_v4_pool')
    pool_v6_pd_family           : int   | Empty = Field(default_factory=Empty, alias='pool_v6_pd_family')
    pool_v6_pd_name             : str   | Empty = Field(default_factory=Empty, alias='pool_v6_pd_name')
    pool_v6_pd_network          : str   | Empty = Field(default_factory=Empty, alias='pool_v6_pd_network')
    pool_v6_pd_pool             : str   | Empty = Field(default_factory=Empty, alias='pool_v6_pd_pool')
    pool_v6_px_family           : int   | Empty = Field(default_factory=Empty, alias='pool_v6_px_family')
    pool_v6_px_name             : str   | Empty = Field(default_factory=Empty, alias='pool_v6_px_name')
    pool_v6_px_network          : str   | Empty = Field(default_factory=Empty, alias='pool_v6_px_network')
    pool_v6_px_pool             : str   | Empty = Field(default_factory=Empty, alias='pool_v6_px_pool')
    profile_pk                  : Any   | Empty = Field(default_factory=Empty, alias='profile_pk')
    rx_byte                     : Any   | Empty = Field(default_factory=Empty, alias='cpe_rx_byte')
    sessions                    : int   | Empty = Field(default_factory=Empty, alias='cpe_sessions')
    state                       : int   | Empty = Field(default_factory=Empty, alias='cpe_state')
    tx_byte                     : Any   | Empty = Field(default_factory=Empty, alias='cpe_tx_byte')
    v4_ip_last                  : str   | Empty = Field(default_factory=Empty, alias='cpe_v4_ip_last')
    v6_pd_last                  : str   | Empty = Field(default_factory=Empty, alias='cpe_v6_pd_last')
    v6_px_last                  : str   | Empty = Field(default_factory=Empty, alias='cpe_v6_px_last')
    wifi_encryption_password    : Any   | Empty = Field(default_factory=Empty, alias='cpe_wifi_encryption_password')

class CPECombo(WSBaseModel):
    pk                          : int           = Field(..., alias='cpe_pk')
    address_pk                  : int   | Empty = Field(default_factory=Empty, alias='address_pk')
    circuit_id                  : str   | Empty = Field(default_factory=Empty, alias='cpe_circuit_id')
    client_complete_name        : str   | Empty = Field(default_factory=Empty, alias='client_complete_name')
    client_pk                   : int   | Empty = Field(default_factory=Empty, alias='client_pk')
    contract_pk                 : int   | Empty = Field(default_factory=Empty, alias='contract_pk')
    dp_name                     : str   | Empty = Field(default_factory=Empty, alias='dp_name')
    dp_pk                       : int   | Empty = Field(default_factory=Empty, alias='dp_pk')
    mac                         : str   | Empty = Field(default_factory=Empty, alias='cpe_mac')
    nas_name                    : str   | Empty = Field(default_factory=Empty, alias='nas_name')
    nas_pk                      : int   | Empty = Field(default_factory=Empty, alias='nas_pk')
    plan_pk                     : int   | Empty = Field(default_factory=Empty, alias='plan_pk')
    pool_v4_pk                  : int   | Empty = Field(default_factory=Empty, alias='pool_v4_pk')
    pool_v6_pd_pk               : int   | Empty = Field(default_factory=Empty, alias='pool_v6_pd_pk')
    pool_v6_px_pk               : int   | Empty = Field(default_factory=Empty, alias='pool_v6_px_pk')
    username                    : str   | Empty = Field(default_factory=Empty, alias='cpe_username')

class CPELocation(WSBaseModel):
    pk                          : int           = Field(..., alias='cpe_pk')
    address                     : Any   | Empty = Field(default_factory=Empty, alias='address')
    address_completation        : Any   | Empty = Field(default_factory=Empty, alias='address_completation')
    address_latitude            : Any   | Empty = Field(default_factory=Empty, alias='address_latitude')
    address_longitude           : Any   | Empty = Field(default_factory=Empty, alias='address_longitude')
    address_neighborhood        : Any   | Empty = Field(default_factory=Empty, alias='address_neighborhood')
    address_number              : Any   | Empty = Field(default_factory=Empty, alias='address_number')
    address_pk                  : Any   | Empty = Field(default_factory=Empty, alias='address_pk')
    address_province            : Any   | Empty = Field(default_factory=Empty, alias='address_province')
    address_state               : Any   | Empty = Field(default_factory=Empty, alias='address_state')
    address_zipcode             : Any   | Empty = Field(default_factory=Empty, alias='address_zipcode')
    circuit_id                  : str   | Empty = Field(default_factory=Empty, alias='cpe_circuit_id')
    client_complete_name        : Any   | Empty = Field(default_factory=Empty, alias='client_complete_name')
    client_pk                   : int   | Empty = Field(default_factory=Empty, alias='client_pk')
    contract_amount             : Any   | Empty = Field(default_factory=Empty, alias='contract_amount')
    contract_deleted            : Any   | Empty = Field(default_factory=Empty, alias='contract_deleted')
    contract_number             : Any   | Empty = Field(default_factory=Empty, alias='contract_number')
    contract_pay_day            : Any   | Empty = Field(default_factory=Empty, alias='contract_pay_day')
    contract_pk                 : Any   | Empty = Field(default_factory=Empty, alias='contract_pk')
    contract_status             : Any   | Empty = Field(default_factory=Empty, alias='contract_status')
    dp_id                       : Any   | Empty = Field(default_factory=Empty, alias='dp_id')
    dp_name                     : Any   | Empty = Field(default_factory=Empty, alias='dp_name')
    dp_pk                       : Any   | Empty = Field(default_factory=Empty, alias='dp_pk')
    dp_port                     : Any   | Empty = Field(default_factory=Empty, alias='dp_port')
    ds_pk                       : Any   | Empty = Field(default_factory=Empty, alias='ds_pk')
    nas_addr                    : Any   | Empty = Field(default_factory=Empty, alias='nas_addr')
    nas_name                    : Any   | Empty = Field(default_factory=Empty, alias='nas_name')
    nas_pk                      : Any   | Empty = Field(default_factory=Empty, alias='nas_pk')
    offices_pk                  : Any   | Empty = Field(default_factory=Empty, alias='offices_pk')
    plan_name                   : Any   | Empty = Field(default_factory=Empty, alias='plan_name')
    plan_pk                     : Any   | Empty = Field(default_factory=Empty, alias='plan_pk')
    sessions                    : Any   | Empty = Field(default_factory=Empty, alias='cpe_sessions')
    status                      : Any   | Empty = Field(default_factory=Empty, alias='cpe_status')
    username                    : str   | Empty = Field(default_factory=Empty, alias='cpe_username')
