from pydantic import Field

from .olt import OLTVendor
from ...model import Empty, WSBaseModel

class ONU(WSBaseModel):
    client_pk					: int	| Empty = Field(default_factory=Empty, alias='client_pk')
    cpe_pk						: int	| Empty = Field(default_factory=Empty, alias='cpe_pk')
    olt_pk						: int	| Empty = Field(default_factory=Empty, alias='olt_pk')
    frame					    : int	| Empty = Field(default_factory=Empty, alias='frame_id')
    slot						: int	| Empty = Field(default_factory=Empty, alias='slot_id')
    pon						    : int	| Empty = Field(default_factory=Empty, alias='port_id')
    id						    : int	| Empty = Field(default_factory=Empty, alias='onu_id')
    sn					        : str	| Empty = Field(default_factory=Empty, alias='onu_serial')
    name					    : str	| Empty = Field(default_factory=Empty, alias='onu_name')
    wan_tpl_pk					: int	| Empty = Field(default_factory=Empty, alias='wan_tpl_pk')
    wancfg_conntype			    : int	| Empty = Field(default_factory=Empty, alias='onu_wancfg_conntype')
    wancfg_vlanid				: int	| Empty = Field(default_factory=Empty, alias='onu_wancfg_vlanid')
    wancfg_user_vlanid			: int	| Empty = Field(default_factory=Empty, alias='onu_wancfg_user_vlanid')
    wancfg_cos					: int	| Empty = Field(default_factory=Empty, alias='onu_wancfg_cos')
    wancfg_tcont				: int	| Empty = Field(default_factory=Empty, alias='onu_wancfg_tcont')
    wancfg_gemport				: int	| Empty = Field(default_factory=Empty, alias='onu_wancfg_gemport')
    wancfg_svlan				: int	| Empty = Field(default_factory=Empty, alias='onu_wancfg_svlan')
    wancfg_stpid				: int	| Empty = Field(default_factory=Empty, alias='onu_wancfg_stpid')
    wancfg_scos					: int	| Empty = Field(default_factory=Empty, alias='onu_wancfg_scos')
    wancfg_pon_profile			: str	| Empty = Field(default_factory=Empty, alias='onu_wancfg_pon_profile')
    wancfg_pppoe_username		: str	| Empty = Field(default_factory=Empty, alias='onu_wancfg_pppoe_username')
    wancfg_pppoe_passwd			: str	| Empty = Field(default_factory=Empty, alias='onu_wancfg_pppoe_passwd')
    wancfg_pppoe_svcname		: str	| Empty = Field(default_factory=Empty, alias='onu_wancfg_pppoe_svcname')
    wancfg_local_ip				: str	| Empty = Field(default_factory=Empty, alias='onu_wancfg_local_ip')
    web_tpl_pk                  : int   | Empty = Field(default_factory=Empty, alias='web_tpl_pk')
    webcfg_login                : str   | Empty = Field(default_factory=Empty, alias='onu_webcfg_login')
    webcfg_password             : str   | Empty = Field(default_factory=Empty, alias='onu_webcfg_password')
    wifi_tpl_pk                 : int   | Empty = Field(default_factory=Empty, alias='wifi_tpl_pk')
    wificfg_name                : str   | Empty = Field(default_factory=Empty, alias='onu_wificfg_name')
    wificfg_password            : str   | Empty = Field(default_factory=Empty, alias='onu_wificfg_password')

class ONUExtended(ONU):
    pk						    : int               = Field(..., alias='onu_pk')
    client_name					: str	    | Empty = Field(default_factory=Empty, alias='client_name')
    cmd_status				    : int	    | Empty = Field(default_factory=Empty, alias='onu_cmd_status')
    contract_pk					: int	    | Empty = Field(default_factory=Empty, alias='contract_pk')
    contract_number				: int	    | Empty = Field(default_factory=Empty, alias='contract_number')
    cpe_username				: str	    | Empty = Field(default_factory=Empty, alias='cpe_username')
    cpe_circuit_id				: str	    | Empty = Field(default_factory=Empty, alias='cpe_circuit_id')
    cpe_dp_port					: int	    | Empty = Field(default_factory=Empty, alias='cpe_dp_port')
    cpe_sessions				: int	    | Empty = Field(default_factory=Empty, alias='cpe_sessions')
    cpe_v4_ip_last				: str	    | Empty = Field(default_factory=Empty, alias='cpe_v4_ip_last')
    cpe_v6_px_last				: str	    | Empty = Field(default_factory=Empty, alias='cpe_v6_px_last')
    cpe_v6_pd_last				: str	    | Empty = Field(default_factory=Empty, alias='cpe_v6_pd_last')
    desc					    : str	    | Empty = Field(default_factory=Empty, alias='onu_desc')
    distance				    : float	    | Empty = Field(default_factory=Empty, alias='onu_distance')
    dp_name						: str	    | Empty = Field(default_factory=Empty, alias='dp_name')
    dp_pk						: int	    | Empty = Field(default_factory=Empty, alias='dp_pk')
    dp_id						: int	    | Empty = Field(default_factory=Empty, alias='dp_id')
    ds_name						: str	    | Empty = Field(default_factory=Empty, alias='ds_name')
    ds_pk						: int	    | Empty = Field(default_factory=Empty, alias='ds_pk')
    info_timer				    : int	    | Empty = Field(default_factory=Empty, alias='onu_info_timer')
    ip						    : str	    | Empty = Field(default_factory=Empty, alias='onu_ip')
    line_profile			    : str	    | Empty = Field(default_factory=Empty, alias='onu_line_profile')
    manager_pk					: int	    | Empty = Field(default_factory=Empty, alias='manager_pk')
    model					    : str	    | Empty = Field(default_factory=Empty, alias='onu_model')
    omddm_current			    : float	    | Empty = Field(default_factory=Empty, alias='onu_omddm_current')
    omddm_temperature		    : float	    | Empty = Field(default_factory=Empty, alias='onu_omddm_temperature')
    omddm_rx_power			    : float	    | Empty = Field(default_factory=Empty, alias='onu_omddm_rx_power')
    omddm_tx_power			    : float	    | Empty = Field(default_factory=Empty, alias='onu_omddm_tx_power')
    omddm_voltage			    : float	    | Empty = Field(default_factory=Empty, alias='onu_omddm_voltage')
    olt_ip						: str	    | Empty = Field(default_factory=Empty, alias='olt_ip')
    olt_name					: str	    | Empty = Field(default_factory=Empty, alias='olt_name')
    olt_omddm_rx_power			: float	    | Empty = Field(default_factory=Empty, alias='olt_omddm_rx_power')
    olt_omddm_tx_power			: float     | Empty = Field(default_factory=Empty, alias='olt_omddm_tx_power')
    olt_vendor				    : OLTVendor	| Empty = Field(default_factory=Empty, alias='olt_vendor')
    onulist_id					: int	    | Empty = Field(default_factory=Empty, alias='onulist_id')
    ponid					    : str	    | Empty = Field(default_factory=Empty, alias='onu_ponid')
    read_db_ts_sec			    : int	    | Empty = Field(default_factory=Empty, alias='onu_read_db_ts_sec')
    rtt						    : int	    | Empty = Field(default_factory=Empty, alias='onu_rtt')
    signal_alert			    : int	    | Empty = Field(default_factory=Empty, alias='onu_signal_alert')
    signal_warning			    : int	    | Empty = Field(default_factory=Empty, alias='onu_signal_warning')
    state					    : str	    | Empty = Field(default_factory=Empty, alias='onu_state')
    vendor					    : str	    | Empty = Field(default_factory=Empty, alias='onu_vendor')
