from pydantic import Field
from typing import Any

from ...model import Empty, WSBaseModel

class Plan(WSBaseModel):
    pk                  : int                   = Field(..., alias='plan_pk')
    addresslist         : str           | Empty = Field(default_factory=Empty, alias='plan_addresslist')
    amount              : float         | Empty = Field(default_factory=Empty, alias='plan_amount')
    business            : bool          | Empty = Field(default_factory=Empty, alias='plan_business')
    color               : str           | Empty = Field(default_factory=Empty, alias='plan_color')
    desc                : str           | Empty = Field(default_factory=Empty, alias='plan_desc')
    kv                  : Any           | Empty = Field(default_factory=Empty, alias='plan_kv')
    hs_active           : bool          | Empty = Field(default_factory=Empty, alias='plan_hs_active')
    hs_cable            : bool          | Empty = Field(default_factory=Empty, alias='plan_hs_cable')
    hs_description      : str           | Empty = Field(default_factory=Empty, alias='plan_hs_description')
    hs_detail           : str           | Empty = Field(default_factory=Empty, alias='plan_hs_detail')
    hs_featured         : bool          | Empty = Field(default_factory=Empty, alias='plan_hs_featured')
    hs_fiber            : bool          | Empty = Field(default_factory=Empty, alias='plan_hs_fiber')
    hs_name             : str           | Empty = Field(default_factory=Empty, alias='plan_hs_name')
    hs_promotional      : bool          | Empty = Field(default_factory=Empty, alias='plan_hs_promotional')
    hs_radio            : bool          | Empty = Field(default_factory=Empty, alias='plan_hs_radio')
    hs_show_speed       : bool          | Empty = Field(default_factory=Empty, alias='plan_hs_show_speed')
    hs_show_turbo_speed : bool          | Empty = Field(default_factory=Empty, alias='plan_hs_show_turbo_speed')
    hs_show_turbo_time  : bool          | Empty = Field(default_factory=Empty, alias='plan_hs_show_turbo_time')
    limit_active        : bool          | Empty = Field(default_factory=Empty, alias='plan_limit_active')
    limit_info          : str           | Empty = Field(default_factory=Empty, alias='plan_limit_info')
    name                : str           | Empty = Field(default_factory=Empty, alias='plan_name')
    offices_pk          : int           | Empty = Field(default_factory=Empty, alias='offices_pk')
    priority            : int           | Empty = Field(default_factory=Empty, alias='plan_priority')
    prod_cean           : int           | Empty = Field(default_factory=Empty, alias='plan_prod_cean')
    prod_ncm            : int           | Empty = Field(default_factory=Empty, alias='plan_prod_ncm')
    residential         : bool          | Empty = Field(default_factory=Empty, alias='plan_residential')
    rural               : bool          | Empty = Field(default_factory=Empty, alias='plan_rural')
    rx_burst            : int           | Empty = Field(default_factory=Empty, alias='plan_rx_burst')
    rx_burst_th         : int           | Empty = Field(default_factory=Empty, alias='plan_rx_burst_th')
    rx_burst_time       : int           | Empty = Field(default_factory=Empty, alias='plan_rx_burst_time')
    rx_huawei_cbs       : int           | Empty = Field(default_factory=Empty, alias='plan_rx_huawei_cbs')
    rx_min              : int           | Empty = Field(default_factory=Empty, alias='plan_rx_min')
    rx_nominal          : int           | Empty = Field(default_factory=Empty, alias='plan_rx_nominal')
    rx_reduced          : int           | Empty = Field(default_factory=Empty, alias='plan_rx_reduced')
    rx_speed            : int           | Empty = Field(default_factory=Empty, alias='plan_rx_speed')
    tag                 : str           | Empty = Field(default_factory=Empty, alias='plan_tag')
    tag_rate            : str           | Empty = Field(default_factory=Empty, alias='plan_tag_rate')
    tax_bc              : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_bc')
    tax_model           : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_model')
    tx_burst            : int           | Empty = Field(default_factory=Empty, alias='plan_tx_burst')
    tx_burst_th         : int           | Empty = Field(default_factory=Empty, alias='plan_tx_burst_th')
    tx_burst_time       : int           | Empty = Field(default_factory=Empty, alias='plan_tx_burst_time')
    tx_huawei_cbs       : int           | Empty = Field(default_factory=Empty, alias='plan_tx_huawei_cbs')
    tx_min              : int           | Empty = Field(default_factory=Empty, alias='plan_tx_min')
    tx_nominal          : int           | Empty = Field(default_factory=Empty, alias='plan_tx_nominal')
    tx_reduced          : int           | Empty = Field(default_factory=Empty, alias='plan_tx_reduced')
    tx_speed            : int           | Empty = Field(default_factory=Empty, alias='plan_tx_speed')
    tax_trib_pk         : int           | Empty = Field(default_factory=Empty, alias='tax_trib_pk')
    turbo_active        : bool          | Empty = Field(default_factory=Empty, alias='plan_turbo_active')
    turbo_ontimes       : str           | Empty = Field(default_factory=Empty, alias='plan_turbo_ontimes')

class PlanExtended(Plan):
    active              : bool          | Empty = Field(default_factory=Empty, alias='plan_active')
    amount_max          : float         | Empty = Field(default_factory=Empty, alias='plan_amount_max')
    amount_min          : float         | Empty = Field(default_factory=Empty, alias='plan_amount_min')
    client_max          : Any           | Empty = Field(default_factory=Empty, alias='plan_client_max')
    client_type         : Any           | Empty = Field(default_factory=Empty, alias='plan_client_type')
    contract_max        : Any           | Empty = Field(default_factory=Empty, alias='plan_contract_max')
    deleted             : bool          | Empty = Field(default_factory=Empty, alias='plan_deleted')
    invoice_max         : Any           | Empty = Field(default_factory=Empty, alias='plan_invoice_max')
    item_type           : Any           | Empty = Field(default_factory=Empty, alias='plan_item_type')
    tax_aliq_cofins     : float         | Empty = Field(default_factory=Empty, alias='plan_tax_aliq_cofins')
    tax_aliq_icms       : float         | Empty = Field(default_factory=Empty, alias='plan_tax_aliq_icms')
    tax_aliq_iss        : float         | Empty = Field(default_factory=Empty, alias='plan_tax_aliq_iss')
    tax_aliq_pis_pasep  : float         | Empty = Field(default_factory=Empty, alias='plan_tax_aliq_pis_pasep')
    tax_aliq_reduction  : float         | Empty = Field(default_factory=Empty, alias='plan_tax_aliq_reduction')
    tax_class           : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_class')
    tax_cnae            : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_cnae')
    tax_discount        : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_discount')
    tax_item_agg        : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_item_agg')
    tax_item_code       : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_item_code')
    tax_others          : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_others')
    tax_qtd_ctt         : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_qtd_ctt')
    tax_qtd_fat         : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_qtd_fat')
    tax_qtd_prov        : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_qtd_prov')
    tax_tariff          : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_tariff')
    tax_taxable         : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_taxable')
    tax_total           : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_total')
    tax_trib_code_mun   : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_trib_code_mun')
    tax_type            : Any           | Empty = Field(default_factory=Empty, alias='plan_tax_type')


